### ISSUE TITLE
How to collect and analyse tweets from a generic list of accounts?

### ISSUE THREAD

**Issue by hueper** [sebastiansauer/polits_tweet_mining#2]
I'd like to collect and analyse tweets from a generic list of accounts. What would be the preferred way to achieve this? How should the list of accounts look like? Where should the list be saved?

In your file [code/02_get_accounts.R in line 11](https://github.com/sebastiansauer/polits_tweet_mining/blob/master/code/02_get_accounts.R#L11), your refer to a csv file "../data_polit_twitter/raw/german_politicians_twitter_raw.csv". I guess this would be the input for further steps? How is this csv created and what's its scheme?

Best,
Moritz

**Comment by sebastiansauer** [comment]
Hi Moritz,

I had forgotten to include this account list data file - it's now uploaded under `data/`. 

This file was created more or less manually. It's a csv file with the columns 
`screenName,name,party,human`

`human` is simply indicating whether it's a person (ie., politician) or a batch account (eg., for general notes from a given political party). I only included accounts from real individuals in my analysis.

HTH!

**Comment by hueper** [comment]
cool, thank you!
